### ISSUE TITLE
No dirty validation with custom field

### ISSUE THREAD

**Issue by essarn** [danvick/flutter_form_builder#358] opened 2020-07-08 00:46 UTC
There is no dirty state when validating a custom field, ie. the validation does not wait for the field to get dirty before validating it resulting in that the error text displays directly which is not the expected behavior.

**Comment by essarn** [comment] 2020-07-08 00:52
Solved by manually validating the field at appropriate stages instead of using auto validation. The issue is however left open since the underlying problem is not solved.

**Comment by danvick** [comment] 2020-07-08 17:22
> There is no dirty state when validating a custom field, ie. the validation does not wait for the field to get dirty before validating it resulting in that the error text displays directly which is not the expected behavior.

Hello @essarn,

Kindly note that this is the default behavior of Flutter's Form.

I'm working on this feature in v4.0.0 of the package, which is [still in the works](https://pub.dev/packages/flutter_form_builder/versions/4.0.0-alpha.4). It's however not quite straight forward in Flutter's context. 

Any help in achieving this will be highly appreciated.

Cheers.

**Comment by essarn** [comment] 2020-07-08 20:33
@danvick 

You are right that this is the default behavior in Flutter. Might be good to wait for https://github.com/flutter/flutter/pull/59766 before doing any work on this though.

**Comment by danvick** [comment] 2020-07-08 20:35
My hack seems to be working well enough though :-)
Thanks for the info.

**Comment by danvick** [comment] 2020-08-05 11:37
Duplicate of #29

**Closed by danvick** 2020-08-05 11:37 UTC
Labels: duplicate, enhancement, good first issue
