### ISSUE TITLE
Signature To PNG or JPG

### ISSUE THREAD

**Issue by TafadzwaD** [danvick/flutter_form_builder#345] opened 2020-06-25 02:09 UTC
How do i save the image to JPEG or any other image format?

Thanks you for this wonderful package @danvick

**Comment by danvick** [comment] 2020-06-25 11:19
Hi @TafadzwaD,
`Image image = Image.memory(data);` will do the trick.

PS: I'm glad you find the package useful.

**Comment by danvick** [comment] 2020-06-25 11:21
For reference purposes, this is a duplicate of #218

**Comment by TafadzwaD** [comment] 2020-06-25 21:48
Thank you for the prompt response @danvick . Worked for me!!!👏👏👏👏👏👏👏

**Closed** 2020-07-18 18:34 UTC
Labels: duplicate, question, solved
