### ISSUE TITLE
FormBuilderChipsInput validator error

### ISSUE THREAD

**Issue by danielweil** [danvick/flutter_form_builder#658] opened 2020-12-24 16:47 UTC
Hi Guys,

I just discovered that I cannot use required validator in FormBuilderChipsInput that it starts to give a flutter framework error.

![image](https://user-images.githubusercontent.com/44274213/103099722-5b3a1c00-45ee-11eb-9f7e-17c6e2271ec0.png)

![photo5127839799649085607](https://user-images.githubusercontent.com/44274213/103099744-7311a000-45ee-11eb-8437-2c241b87c01d.jpg)

Thanks!

**Comment by andrewzakhartchouk** [comment] 2020-12-25 01:33
This is the same issue for FilterChip too.
![image](https://user-images.githubusercontent.com/65052923/103113118-97c45100-469c-11eb-9a6c-2788dc4303bf.png)

**Comment by danvick** [comment] 2020-12-29 05:19
Hi @danielweil / @andrewzakhartchouk 
Thanks for bringing the issue to my attention. 

For now, consider declaring the generic type on the widget like so: `FormBuilderChipsInput<String>` or `FormBuilderFilterChip<int>`.

**Comment by danvick** [comment] 2020-12-29 05:30
Hi @awhitford,
This issue seems to originate [from this line](https://github.com/danvick/flutter_form_builder/blob/8830310eba0c225fec204ba81d690c1a6caff301/lib/src/fields/form_builder_filter_chips.dart#L41) where, in the effort to have our code well-typed, we are declaring the validator to be of type `FormFieldValidator<List<T>>`. 

The problem with this is that if the generic type `T` is not explicitly declared when creating the widget, the type `T` is not known, and for some reason, it's being replaced by `Null`. To solve this issue I'm considering  having  it  as `FormFieldValidator<List> validator,`

**Comment by awhitford** [comment] 2020-12-29 05:40
I do not like the idea of trying to defeat the type system.  I usually see issues where people aren't being consistently clear on type, so Dart needs to fall back to something abstract like _dynamic_.  We may instead be missing something trivial, like saying `<T>[]` -- but I didn't think that is necessary when the assignment type is `List<T>`.  (I fixed something minor in #611 by _adding_ a missing type declaration, not _relaxing_ the declaration.)  Show me an example code snippet that I can analyze.

**Comment by danvick** [comment] 2020-12-29 05:43
In the example project, if you add a validator, you'll be able to reproduce.

**Comment by awhitford** [comment] 2020-12-29 06:04
The VS Code hover message clearly says that **Dart is unable to infer the type**.  This actually makes sense -- what is going to tell the type when you don't specify a `<T>`?  A natural thing is `initialValue` -- but if you exclude that, then what else is used?  Well, maybe the `validators`, but if you omit the `<T>` from those, then again Dart has no information.

Consider this code:
```dart
                  FormBuilderFilterChip(
                    name: 'filter_chip',
                    enabled: false,
                    decoration: const InputDecoration(
                      labelText: 'Select many options',
                    ),
                    initialValue: ['Test', 'Test 1', 'Test 2'],
                    maxChips: 3,
                    options: [
                      FormBuilderFieldOption(
                          value: 'Test', child: Text('Test')),
                      FormBuilderFieldOption(
                          value: 'Test 1', child: Text('Test 1')),
                      FormBuilderFieldOption(
                          value: 'Test 2', child: Text('Test 2')),
                      FormBuilderFieldOption(
                          value: 'Test 3', child: Text('Test 3')),
                      FormBuilderFieldOption(
                          value: 'Test 4', child: Text('Test 4')),
                    ],
                  ),
```

The type is not mentioned in the `FormBuilderFilterChip` declaration. However, **Dart is able to infer the type** from the `initialValue` property, which is a `List<String>`, so `T` is `String`.

The type is also not mentioned in the `FormBuilderFieldOption` declaration.  However, **Dart is able to infer the type** from the `value` property, which is a `String`, so `T` is `String`.  (And `options` is a `List<FormBuilderFieldOption<String>> options`.)

The easiest thing to do is to specify the type when declaring `FormBuilderFilterChip`.  Dart doesn't know, but the developer should know.  Help out Dart so that it can generate the _best_ code:  `FormBuilderFilterChip<String>` or `FormBuilderFilterChip<int>` -- whatever makes sense.

In general, `dynamic` is a code smell; usually there is a more appropriate _type_ declaration to specify -- and then the compiler can do much better static code analysis and may identify bugs at compile-time.

**Comment by awhitford** [comment] 2020-12-29 06:20
For the  `FormBuilderChipsInput<Contact>` example, I added this:
```dart
                    validator: FormBuilderValidators.compose([
                      FormBuilderValidators.required(context),
                    ]),
```
and it behaved fine because the type is clear.

Similarly, I added the validator to the `FormBuilderChoiceChip` example:
```dart
                  FormBuilderChoiceChip(
                    name: 'choice_chip',
                    decoration: const InputDecoration(
                      labelText: 'Select an option',
                    ),
                    options: [
                      FormBuilderFieldOption(
                          value: 'Test', child: Text('Test')),
                      FormBuilderFieldOption(
                          value: 'Test 1', child: Text('Test 1')),
                      FormBuilderFieldOption(
                          value: 'Test 2', child: Text('Test 2')),
                      FormBuilderFieldOption(
                          value: 'Test 3', child: Text('Test 3')),
                      FormBuilderFieldOption(
                          value: 'Test 4', child: Text('Test 4')),
                    ],
                    validator: FormBuilderValidators.compose([
                      FormBuilderValidators.required(context),
                    ]),
                  ),
```
and it also behaved correctly.  Note that the `FormBuilderChoiceChip` example correctly infers `T` as `String` because the `options` are `List<FormBuilderFieldOption<String>>`.

In summary, I do not advocate for any change.  Instead, the **developer needs to ensure that the type is being properly _declared_ or _inferred_.** (This is just how Dart works.)

Projects can proactively identify missing type information by activating analyzer rules -- just like how FFB does this:
* https://github.com/danvick/flutter_form_builder/blob/master/analysis_options.yaml

**Comment by awhitford** [comment] 2020-12-29 06:30
> This is the same issue for FilterChip too.
> ![image](https://user-images.githubusercontent.com/65052923/103113118-97c45100-469c-11eb-9a6c-2788dc4303bf.png)
> 
> It is pulling from an array mapped to FormBuilderFieldOptions. Using a regular list has the same issue.

@andrewzakhartchouk Based on this message, your `validator` may be faulty.  What exactly do you have declared?  I'd like to see the whole widget declaration if you can.

**Comment by andrewzakhartchouk** [comment] 2021-01-05 02:51
> @andrewzakhartchouk Based on this message, your `validator` may be faulty. What exactly do you have declared? I'd like to see the whole widget declaration if you can.

@awhitford Here we are. I'm not in need of a validator for this particular portion, but am I correct in guessing it might have to do with my options (array being mapped and then toList)? 

![image](https://user-images.githubusercontent.com/65052923/103600802-a4be2b80-4f4b-11eb-9991-aadc2ff1e6a6.png)

**Comment by awhitford** [comment] 2021-01-05 04:04
@andrewzakhartchouk Generating `options` from `_symptoms` is not really a problem.  However, with the above code, Dart doesn't have enough information to _infer the type_, and is falling back to _dynamic_.  To address this, help Dart out by being explicit.

The easiest thing to do is to specify the type when declaring `FormBuilderFilterChip`.  For example, if this is for `String` values, then the declaration should be, `FormBuilderFilterChip<String>` (line 1).  That is enough to add type information to `validator` and `options`.  When specifying a type at the top, that also specifies a type for `validator` and `options`.

If you are using _VS Code_, you can hover over items to see the type information.

**Comment by andrewzakhartchouk** [comment] 2021-01-05 05:29
That makes sense. Tested and it works. Thanks for the advice.

**Comment by awhitford** [comment] 2021-01-05 06:11
@andrewzakhartchouk Great to hear!

Closing this issue because it seems invalid.  If people run into this issue, they need to ensure that the _type_ is specified.

**Closed by awhitford** 2021-01-05 06:11 UTC
