### ISSUE TITLE
How to request focus to first field

### ISSUE THREAD

**Issue by ecuellar** [danvick/flutter_form_builder#371] opened 2020-07-19 16:06 UTC
Hi, not all the FormFields, has an autofocus or focusNode property (for example Dropdown, Radio, chips).

How can I request the focus for the first field?

**Comment by danvick** [comment] 2020-07-20 18:07
This may be a duplicate of #54 which is planned for v4.0.0 Milestone.

**Closed by danvick** 2020-07-20 18:07 UTC
Labels: duplicate, enhancement
