### ISSUE TITLE
How to clear errors when value is changed to valid

### ISSUE THREAD

**Issue by vimalmistry** [danvick/flutter_form_builder#232] opened 2020-02-20 21:08 UTC
#Question 
 I want to clear message while value has been changed to valid. For now it cleared when we hit submit button.

**Comment by danvick** [comment] 2020-02-27 13:50
You can set `autovalidate` to `true` on either the whole form or the field. 

The problem with that method is that validation will run even before any input is done by the user, that's a Flutter issue and not necessarily an issue with this package.

**Comment by BigBrosh** [comment] 2020-03-15 16:30
"The problem with that method is that validation will run even before any input is done by the user, that's a Flutter issue and not necessarily an issue with this package."

I just faced this issue
It's definitely wrong UX
As a user I want to validate field either after I make some changes or focus the field

I came up with this solution
Maybe I'm wrong, maybe I don't, but I've got desired behavior
@danvick please, take a look and tell if it's possible to implement this

`class TextField extends StatefulWidget {

  @override
  _FTextFieldState createState() => _FTextFieldState();
}

class _TextFieldState extends State<TextField> {
  bool pristine = true;

  void activate() {
    setState(() {
      pristine = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return FormBuilderTextField(
        attribute: 'login',
        autovalidate: !pristine,
        maxLines: 1,
        onChanged: (value) => activate(),
        decoration: InputDecoration(labelText: 'Login'),
        validators: [
          FormBuilderValidators.required()
        ]
    );
  }
}`

**Comment by danvick** [comment] 2020-08-05 10:30
Duplicate of #29.

**Closed by danvick** 2020-08-05 10:30 UTC
Labels: duplicate

**Comment by mzl1988** [comment] 2020-09-15 09:58
onChanged: (value) {
                      _fbKey.currentState.fields['lastName'].currentState
                          .validate();
                    },
