### ISSUE TITLE
FormBuilderSignaturePad initialValue issue

### ISSUE THREAD

**Issue by janardhanmupparaju** [danvick/flutter_form_builder#173] opened 2019-11-12 15:37 UTC
I am trying to give initial value to FormBuilderSignaturePad but it is not displaying old signature.

this is code
  final GlobalKey<FormBuilderState> _fbKey = GlobalKey<FormBuilderState>();

Container(
            child: FormBuilder(
            key: _fbKey,
            autovalidate: true,
            child: FormBuilderSignaturePad(
              initialValue: Singleton.signatureImage == null
                  ? null
                  : Singleton.signatureImage,
              decoration: InputDecoration(
                  labelText: "Signature", border: InputBorder.none),
              penColor: Colors.blue,
              onChanged: (value) async {
              setState(() {
              Singleton.signatureImagePath = value;
              });
              },
              attribute: "signature",
              height: 100,
            ),
          ));

**Comment by danvick** [comment] 2019-11-17 09:42
Hi @janardhanmupparaju,
This is a known issue. The problem is that the [underlying package](https://github.com/4Q-s-r-o/signature) we use for the field expects a list of points as the input and not an image.
Currently, I haven't figured out a way to convert an image to a list of points for the `initialValue` to work.

**Comment by danvick** [comment] 2020-07-18 18:18
Fixed in latest versions of the library

**Closed by danvick** 2020-07-18 18:18 UTC
Labels: enhancement, wontfix
