### ISSUE TITLE
I am getting an error on the Type Ahead when I return a List<Entity> to the suggestionsCallback

### ISSUE THREAD

**Issue by metaltigerfish** [danvick/flutter_form_builder#21] opened 2019-01-23 18:13 UTC
controls: [
            FormBuilderInput.typeAhead(
              label: 'Team 1',
              attribute: 'team1',
              require: true,
              //value: team1name,
              itemBuilder: (context, team1) {
                return ListTile(
                  title: Text(team1.name),
                );
              },
              suggestionsCallback: (query) async {
                BlocProvider.of(context).dataBloc.typeAheadQuery.add(query);
                return await BlocProvider.of(context)
                    .dataBloc
                    .typeAheadValues
                    .last;
              },
            ),
          ],

The suggestions appear fine in the type ahead field suggestion box, but when I click on one of the items in the list I get the following error and the value does not get set to the selected value.

flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: type '_$Entity' is not a subtype of type 'String'

**Comment by danvick** [comment] 2019-01-24 08:18
I think this shows that the `suggestionsCallback` is expecting a list of Strings. Try using a class with a `toString()` implementation.

Kindly note that [flutter_typeahead](https://pub.dartlang.org/packages/flutter_typeahead) is a separate package maintained by another developer. Try raising the issue on [this](https://github.com/AbdulRahmanAlHamali/flutter_typeahead) repo

**Comment by metaltigerfish** [comment] 2019-01-24 18:20
Would it be possible to implement this from the flutter_typeahead

onSuggestionSelected: (suggestion) {
             this._typeAheadController.text = suggestion;
         },

**Comment by danvick** [comment] 2019-01-26 11:55
Meanwhile might I suggest that you map your list of object to a list of strings, I've tried that and it seems to work. Your `suggestionsCallback` would end up looking similar to:
```
suggestionsCallback: (query) {
                var contacts = [
                  AppProfile('Andrew', 'stock@man.com'),
                  AppProfile('Brian', 'brian@flutter.io'),
                  AppProfile('Fred', 'fred@google.com'),
                  AppProfile('John', 'john@flutter.io'),
                  AppProfile('Paul', 'paul@google.com'),
                  AppProfile('Thomas', 'thomas@flutter.io')
                ];
                var contactsNames = contacts
                    .map((contact) => "${contact.name} <${contact.email}>")
                    .toList(growable: false);
                if (query.length != 0) {
                  var lowercaseQuery = query.toLowerCase();
                  return contactsNames.where((country) {
                    return country.toLowerCase().contains(lowercaseQuery);
                  }).toList(growable: false)
                    ..sort((a, b) => a
                        .toLowerCase()
                        .indexOf(lowercaseQuery)
                        .compareTo(b.toLowerCase().indexOf(lowercaseQuery)));
                } else {
                  return contactsNames;
                }
},
```

**Comment by danvick** [comment] 2019-01-28 09:50
I'm gonna consider this elegant enough of a solution and close this issue since it doesn't directly relate to this package.

**Comment by aytunch** [comment] 2019-06-24 19:44
@danvick I think your solution helps get rid of the error but inside of the code, we are still not be able to get the whole class object whose name is selected. [I opened up an issue as you suggested in flutter_typeahead](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/113). Most of the time user will be getting the suggestions from a backend as objects and we would like to process the object instead of just its .toString() version. Any help would be greatly appreciated. And thanks for this great package.

**Comment by danvick** [comment] 2019-06-25 08:27
I will consider working on the issue. The problem is that `flutter_typeahead` only accepts `String` values. 

I've had this issue myself in other projects. 

My workaround for this issue was to use `FormBuilderChipsInput` then set `maxChips` to `1` then get the first element using a `valueTransformer`. I know that sounds complex, I'll share sample code later on when I have time.

**Comment by aytunch** [comment] 2019-06-25 10:01
Thats a very interesting workaround @danvick i would love to see the code if possible. Because i have every other module in my form working other than this type ahead and i cant go forward without it. I use google places api to get suggestions. Everything in the form
Looks great. Thanks for this package.  Meanwhile I hope author of typeahead spends sometime on this issue as well since its that packages main responsibility to have support for this issue. But again i am ok with a workaround atm since i need to get the suggested object instead of the string to go forward.

**Comment by danvick** [comment] 2019-06-25 10:28
Try this out. Let me know if you have any questions.

```dart
FormBuilderChipsInput(
  decoration:
      InputDecoration(labelText: "Contact Name"),
  attribute: 'contact',
  maxChips: 1, //Allow only one chip
  valueTransformer: (val) => val?[0], //Pick the first element from the array
  findSuggestions: (String query) async {
    List<Contact> contacts = await _fetchContacts();
    if (query.length != 0) {
      var lowercaseQuery = query.toLowerCase();
      return contacts.where((contact) {
        return contact.name
            .toLowerCase()
            .contains(query.toLowerCase());
      }).toList(growable: false)
        ..sort((a, b) => a.name
            .toLowerCase()
            .indexOf(lowercaseQuery)
            .compareTo(b.name
                .toLowerCase()
                .indexOf(lowercaseQuery)));
    } else {
      return [];
    }
  },
  chipBuilder: (context, state, contact) {
    return InputChip(
      key: ObjectKey(contact),
      label: Text('${contact.name}'),
      onDeleted: () => state.deleteChip(contact),
      materialTapTargetSize:
          MaterialTapTargetSize.shrinkWrap,
    );
  },
  suggestionBuilder: (context, state, contact) {
    return ListTile(
      key: ObjectKey(contact),
      title: Text('${contact.name}'),
      subtitle: Text('${contact.email}'),
      onTap: () => state.selectSuggestion(contact),
    );
  },
),
```

**Comment by aytunch** [comment] 2019-06-25 15:05
This look very well and even better for my use case. Thanks @danvick :) However, one thing I could't get to work was constructing the initial suggestion list when query string is empty and the text box is pressed. 

I have a list of places which are around the users location and when the user presses the `FormBuilderChipsInput` and before types anything I want to show the suggestions. And when he/she types a letter I want to change suggestions. The second part works as of now but the initial suggestions don't work. Do you know how to trigger it?

**Comment by danvick** [comment] 2019-06-25 15:10
Within `findSuggestions` the line that reads:
```dart
else {
      return [];
}
```
change it to:
```dart
else {
      return places;
}
```
or whatever your equivalent of your code is.

**Comment by aytunch** [comment] 2019-06-25 15:35
Thats how I have it at the moment but it doesn't show the initial suggestions when I touch and gain focus on the textinputview:/ 

It works only after I type a letter and then backspace. But it doesn't trigger in the beginning.

Is there a way to fire `findSuggestions` when the controller gains focus?

**Comment by aytunch** [comment] 2019-06-25 15:45
@danvick Also some part of my suggestion list stays under the keyboard. Is there a way to limit it? Sorry for bothering you this much:/

**Comment by danvick** [comment] 2019-06-26 05:46
Since I'm the maintainer of `ChipsInput`, I'll try to work on the issues you've raised. I may not be able to do it immediately but can I request you to close this issue then open the issues related to `ChipsInput` [here](https://github.com/danvick/flutter_chips_input/issues)

**Comment by aytunch** [comment] 2019-06-26 08:16
I will do what you asked for in detail in a couple of hours when i am
In front of my computer. Take care

**Closed** 2019-06-26 08:23 UTC

**Comment by JohnKuan** [comment] 2019-08-22 07:04
@danvick I have opened a pull request to allow control of the text to update onto TextEditingController. It has an assert statement to check if T is not of type String. Let me know if this works.
[https://github.com/danvick/flutter_form_builder/pull/115](url)

**Comment by Marcosmaliki** [comment] 2021-11-11 07:01
Is it possible to use TypeAhead as an autocomplete textfield? It works great  when an item from the list is selected. 
I need a way to use the list only as suggestions but also accept new text from the user

**Comment by yeswa-test** [comment] 2024-07-12 06:38
suggestionCallback isn't a type gives on my migrating project
