### ISSUE TITLE
Error: Type 'MouseCursor' not found

### ISSUE THREAD

**Issue by Windol** [danvick/flutter_form_builder#418] opened 2020-08-14 15:54 UTC
In my development environment, I'm having trouble running a simple example using flutter_form_builder. Can anyone help me identify the cause?
```console
> flutter run
Launching lib\main.dart on SM J200BT in debug mode...
Running Gradle task 'assembleDebug'...                          

Compiler message:

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:28:9: Error: Type 'MouseCursor' not found.

  final MouseCursor mouseCursor;

        ^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:151:9: Error: Type 'TimePickerEntryMode' not found.

  final TimePickerEntryMode timePickerInitialEntryMode;

        ^^^^^^^^^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_slider.dart:36:9: Error: Type 'MouseCursor' not found.

  final MouseCursor mouseCursor;

        ^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_switch.dart:67:9: Error: Type 'MouseCursor' not found.

  final MouseCursor mouseCursor;

        ^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.9.1/lib/src/chips_input.dart:392:3: Error: Type 'AutofillScope' not found.

  AutofillScope get currentAutofillScope => null;

  ^^^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:28:9: Error: 'MouseCursor' isn't a type.

  final MouseCursor mouseCursor;

        ^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:101:7: Error: No named parameter with the name 'mouseCursor'.

      mouseCursor: widget.mouseCursor,

      ^^^^^^^^^^^

/C:/tools/flutter/packages/flutter/lib/src/material/checkbox.dart:58:9: Context: Found this candidate, but the arguments don't match.

  const Checkbox({

        ^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:151:9: Error: 'TimePickerEntryMode' isn't a type.

  final TimePickerEntryMode timePickerInitialEntryMode;

        ^^^^^^^^^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:220:39: Error: Getter not found: 'TimePickerEntryMode'.

    this.timePickerInitialEntryMode = TimePickerEntryMode.dial,

                                      ^^^^^^^^^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:403:9: Error: No named parameter with the name 'currentDate'.

        currentDate: widget.currentDate,

        ^^^^^^^^^^^

/C:/tools/flutter/packages/flutter/lib/src/material/pickers/date_picker_dialog.dart:91:18: Context: Found this candidate, but the arguments don't match.

Future<DateTime> showDatePicker({

                 ^^^^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:436:9: Error: No named parameter with the name 'initialEntryMode'.

        initialEntryMode: widget.timePickerInitialEntryMode,

        ^^^^^^^^^^^^^^^^

/C:/tools/flutter/packages/flutter/lib/src/material/time_picker.dart:1803:19: Context: Found this candidate, but the arguments don't match.

Future<TimeOfDay> showTimePicker({

                  ^^^^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_slider.dart:36:9: Error: 'MouseCursor' isn't a type.

  final MouseCursor mouseCursor;

        ^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_slider.dart:138:19: Error: No named parameter with the name 'focusNode'.

                  focusNode: widget.focusNode,

                  ^^^^^^^^^

/C:/tools/flutter/packages/flutter/lib/src/material/slider.dart:114:9: Context: Found this candidate, but the arguments don't match.

  const Slider({

        ^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_switch.dart:67:9: Error: 'MouseCursor' isn't a type.

  final MouseCursor mouseCursor;

        ^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_switch.dart:179:17: Error: No named parameter with the name 'mouseCursor'.

                mouseCursor: widget.mouseCursor,

                ^^^^^^^^^^^

/C:/tools/flutter/packages/flutter/lib/src/material/switch.dart:65:9: Context: Found this candidate, but the arguments don't match.

  const Switch({

        ^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_text_field.dart:199:7: Error: No named parameter with the name 'autofillHints'.

      autofillHints: widget.autofillHints,

      ^^^^^^^^^^^^^

/C:/tools/flutter/packages/flutter/lib/src/material/text_form_field.dart:131:3: Context: Found this candidate, but the arguments don't match.

  TextFormField({

  ^^^^^^^^^^^^^



Compiler message:

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:28:9: Error: Type 'MouseCursor' not found.

  final MouseCursor mouseCursor;

        ^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:151:9: Error: Type 'TimePickerEntryMode' not found.

  final TimePickerEntryMode timePickerInitialEntryMode;

        ^^^^^^^^^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_slider.dart:36:9: Error: Type 'MouseCursor' not found.

  final MouseCursor mouseCursor;

        ^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_switch.dart:67:9: Error: Type 'MouseCursor' not found.

  final MouseCursor mouseCursor;

        ^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.9.1/lib/src/chips_input.dart:392:3: Error: Type 'AutofillScope' not found.

  AutofillScope get currentAutofillScope => null;

  ^^^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:28:9: Error: 'MouseCursor' isn't a type.

  final MouseCursor mouseCursor;

        ^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:101:7: Error: No named parameter with the name 'mouseCursor'.

      mouseCursor: widget.mouseCursor,

      ^^^^^^^^^^^

/C:/tools/flutter/packages/flutter/lib/src/material/checkbox.dart:58:9: Context: Found this candidate, but the arguments don't match.

  const Checkbox({

        ^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:151:9: Error: 'TimePickerEntryMode' isn't a type.

  final TimePickerEntryMode timePickerInitialEntryMode;

        ^^^^^^^^^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:220:39: Error: Getter not found: 'TimePickerEntryMode'.

    this.timePickerInitialEntryMode = TimePickerEntryMode.dial,

                                      ^^^^^^^^^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:403:9: Error: No named parameter with the name 'currentDate'.

        currentDate: widget.currentDate,

        ^^^^^^^^^^^

/C:/tools/flutter/packages/flutter/lib/src/material/pickers/date_picker_dialog.dart:91:18: Context: Found this candidate, but the arguments don't match.

Future<DateTime> showDatePicker({

                 ^^^^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:436:9: Error: No named parameter with the name 'initialEntryMode'.

        initialEntryMode: widget.timePickerInitialEntryMode,

        ^^^^^^^^^^^^^^^^

/C:/tools/flutter/packages/flutter/lib/src/material/time_picker.dart:1803:19: Context: Found this candidate, but the arguments don't match.

Future<TimeOfDay> showTimePicker({

                  ^^^^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_slider.dart:36:9: Error: 'MouseCursor' isn't a type.

  final MouseCursor mouseCursor;

        ^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_slider.dart:138:19: Error: No named parameter with the name 'focusNode'.

                  focusNode: widget.focusNode,

                  ^^^^^^^^^

/C:/tools/flutter/packages/flutter/lib/src/material/slider.dart:114:9: Context: Found this candidate, but the arguments don't match.

  const Slider({

        ^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_switch.dart:67:9: Error: 'MouseCursor' isn't a type.

  final MouseCursor mouseCursor;

        ^^^^^^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_switch.dart:179:17: Error: No named parameter with the name 'mouseCursor'.

                mouseCursor: widget.mouseCursor,

                ^^^^^^^^^^^

/C:/tools/flutter/packages/flutter/lib/src/material/switch.dart:65:9: Context: Found this candidate, but the arguments don't match.

  const Switch({

        ^^^^^^

/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_text_field.dart:199:7: Error: No named parameter with the name 'autofillHints'.

      autofillHints: widget.autofillHints,

      ^^^^^^^^^^^^^

/C:/tools/flutter/packages/flutter/lib/src/material/text_form_field.dart:131:3: Context: Found this candidate, but the arguments don't match.

  TextFormField({

  ^^^^^^^^^^^^^

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null

build failed.



FAILURE: Build failed with an exception.



* Where:

Script 'C:\tools\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882



* What went wrong:

Execution failed for task ':app:compileFlutterBuildDebug'.

> Process 'command 'C:\tools\flutter\bin\flutter.bat'' finished with non-zero exit value 1



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 31s
Running Gradle task 'assembleDebug'...                             32,4s
Exception: Gradle task assembleDebug failed with exit code 1
```
```console
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [versÃ£o 10.0.18363.1016], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (not installed)
[√] VS Code, 64-bit edition (version 1.47.3)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```
pubspec.yaml
```yaml
name: generate_form
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  schema_form:
    path: ..
  schema_widget: ^1.0.0-5
  logging: ^0.11.4
  json_schema: ^2.2.1
  intl: ^0.16.1
  http: ^0.12.2
  flutter_form_builder: ^3.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
example.dart
```dart
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:logging/logging.dart';

class MyAppFormBuilder extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      locale: Locale("pt", "BR"),
      home: MyFormBuilderHomePage(title: 'Form Builder Demo'),
    );
  }
}

class MyFormBuilderHomePage extends StatelessWidget {
  static final Logger _log = Logger('MyHomePage');

  final GlobalKey<FormBuilderState> _formBuilderKey =
      GlobalKey<FormBuilderState>();

  final String title;

  MyFormBuilderHomePage({Key key, this.title}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
        actions: <Widget>[
          IconButton(icon: Icon(Icons.save), onPressed: _savePressed),
          IconButton(icon: Icon(Icons.delete), onPressed: _resetPressed),
        ],
      ),
      body: FormBuilder(
        key: _formBuilderKey,
        initialValue: {"higroup": "Form Initial Value"},
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            children: <Widget>[
              Text(
                "Form Builder Title",
                style: Theme.of(context).textTheme.headline6,
              ),
              Text(
                "Form Builder Subtitle",
                style: Theme.of(context).textTheme.subtitle1,
              ),
              FormBuilderTextField(
                attribute: "higroup",
                initialValue: "Field Initial Value",
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: <Widget>[
                  RaisedButton(
                    child: Text("Submit"),
                    onPressed: _savePressed,
                  ),
                  RaisedButton(
                    child: Text("Reset"),
                    onPressed: _resetPressed,
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.save),
        onPressed: _savePressed,
      ),
    );
  }

  void _savePressed() {
    final formBuilderState = _formBuilderKey.currentState;

    if (formBuilderState.saveAndValidate()) {
      final formBuilderValue = formBuilderState.value;

      _log.info("formBuilderValue: $formBuilderValue");
    }
  }

  void _resetPressed() {
    _formBuilderKey.currentState.reset();
  }
}
```

**Comment by danvick** [comment] 2020-08-15 10:43
Duplicate of #399

**Closed by danvick** 2020-08-15 10:43 UTC
Labels: duplicate
