### ISSUE TITLE
Flutter version 1.22.0-12.1.pre + flutter_form_builder 3.13.5 - Compile Error form_builder_range_slider

### ISSUE THREAD

**Issue by RodrigoSMarques** [danvick/flutter_form_builder#470] opened 2020-09-21 11:28 UTC
```dart
Xcode's output:
↳
    /Users/rodrigo/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.5/lib/src/fields/form_builder_range_slider.dart:21:9: Error: Type 'RangeSemanticFormatterCallback' not found.
      final RangeSemanticFormatterCallback semanticFormatterCallback;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /Users/rodrigo/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.5/lib/src/fields/form_builder_range_slider.dart:21:9: Error: 'RangeSemanticFormatterCallback' isn't a type.
      final RangeSemanticFormatterCallback semanticFormatterCallback;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by kuhnroyal** [comment] 2020-09-22 15:38
Duplicate of https://github.com/danvick/flutter_form_builder/issues/465

**Closed** 2020-10-03 18:29 UTC
