### ISSUE TITLE
mouse courser not found

### ISSUE THREAD

**Issue by alirizwansaeed** [danvick/flutter_form_builder#420] opened 2020-08-15 08:53 UTC
Launching lib\main.dart on SM A505F in debug mode...

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:28:9: Error: Type 'MouseCursor' not found.
  final MouseCursor mouseCursor;
        ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:151:9: Error: Type 'TimePickerEntryMode' not found.
  final TimePickerEntryMode timePickerInitialEntryMode;
        ^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_slider.dart:36:9: Error: Type 'MouseCursor' not found.
  final MouseCursor mouseCursor;
        ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_switch.dart:67:9: Error: Type 'MouseCursor' not found.
  final MouseCursor mouseCursor;
        ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.9.1/lib/src/chips_input.dart:392:3: Error: Type 'AutofillScope' not found.
  AutofillScope get currentAutofillScope => null;
  ^^^^^^^^^^^^^

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:28:9: Error: Type 'MouseCursor' not found.
  final MouseCursor mouseCursor;
        ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:151:9: Error: Type 'TimePickerEntryMode' not found.
  final TimePickerEntryMode timePickerInitialEntryMode;
        ^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_slider.dart:36:9: Error: Type 'MouseCursor' not found.
  final MouseCursor mouseCursor;
        ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_switch.dart:67:9: Error: Type 'MouseCursor' not found.
  final MouseCursor mouseCursor;
        ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.9.1/lib/src/chips_input.dart:392:3: Error: Type 'AutofillScope' not found.
  AutofillScope get currentAutofillScope => null;
  ^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:28:9: Error: 'MouseCursor' isn't a type.
  final MouseCursor mouseCursor;
        ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:101:7: Error: No named parameter with the name 'mouseCursor'.
      mouseCursor: widget.mouseCursor,
      ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/checkbox.dart:58:9: Context: Found this candidate, but the arguments don't match.
  const Checkbox({
        ^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:151:9: Error: 'TimePickerEntryMode' isn't a type.
  final TimePickerEntryMode timePickerInitialEntryMode;
        ^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:220:39: Error: Getter not found: 'TimePickerEntryMode'.
    this.timePickerInitialEntryMode = TimePickerEntryMode.dial,
                                      ^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:403:9: Error: No named parameter with the name 'currentDate'.
        currentDate: widget.currentDate,
        ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/pickers/date_picker_dialog.dart:91:18: Context: Found this candidate, but the arguments don't match.
Future<DateTime> showDatePicker({
                 ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:436:9: Error: No named parameter with the name 'initialEntryMode'.
        initialEntryMode: widget.timePickerInitialEntryMode,
        ^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/time_picker.dart:1803:19: Context: Found this candidate, but the arguments don't match.
Future<TimeOfDay> showTimePicker({
                  ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_slider.dart:36:9: Error: 'MouseCursor' isn't a type.
  final MouseCursor mouseCursor;
        ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_slider.dart:138:19: Error: No named parameter with the name 'focusNode'.
                  focusNode: widget.focusNode,
                  ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/slider.dart:114:9: Context: Found this candidate, but the arguments don't match.
  const Slider({
        ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_switch.dart:67:9: Error: 'MouseCursor' isn't a type.
  final MouseCursor mouseCursor;
        ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_switch.dart:179:17: Error: No named parameter with the name 'mouseCursor'.
                mouseCursor: widget.mouseCursor,
                ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/switch.dart:65:9: Context: Found this candidate, but the arguments don't match.
  const Switch({
        ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_text_field.dart:199:7: Error: No named parameter with the name 'autofillHints'.
      autofillHints: widget.autofillHints,
      ^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/text_form_field.dart:131:3: Context: Found this candidate, but the arguments don't match.
  TextFormField({
  ^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:28:9: Error: 'MouseCursor' isn't a type.
  final MouseCursor mouseCursor;
        ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:101:7: Error: No named parameter with the name 'mouseCursor'.
      mouseCursor: widget.mouseCursor,
      ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/checkbox.dart:58:9: Context: Found this candidate, but the arguments don't match.
  const Checkbox({
        ^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:151:9: Error: 'TimePickerEntryMode' isn't a type.
  final TimePickerEntryMode timePickerInitialEntryMode;
        ^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:220:39: Error: Getter not found: 'TimePickerEntryMode'.
    this.timePickerInitialEntryMode = TimePickerEntryMode.dial,
                                      ^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:403:9: Error: No named parameter with the name 'currentDate'.
        currentDate: widget.currentDate,
        ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/pickers/date_picker_dialog.dart:91:18: Context: Found this candidate, but the arguments don't match.
Future<DateTime> showDatePicker({
                 ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_date_time_picker.dart:436:9: Error: No named parameter with the name 'initialEntryMode'.
        initialEntryMode: widget.timePickerInitialEntryMode,
        ^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/time_picker.dart:1803:19: Context: Found this candidate, but the arguments don't match.
Future<TimeOfDay> showTimePicker({
                  ^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_slider.dart:36:9: Error: 'MouseCursor' isn't a type.
  final MouseCursor mouseCursor;
        ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_slider.dart:138:19: Error: No named parameter with the name 'focusNode'.
                  focusNode: widget.focusNode,
                  ^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/slider.dart:114:9: Context: Found this candidate, but the arguments don't match.
  const Slider({
        ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_switch.dart:67:9: Error: 'MouseCursor' isn't a type.
  final MouseCursor mouseCursor;
        ^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_switch.dart:179:17: Error: No named parameter with the name 'mouseCursor'.
                mouseCursor: widget.mouseCursor,
                ^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/switch.dart:65:9: Context: Found this candidate, but the arguments don't match.
  const Switch({
        ^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_text_field.dart:199:7: Error: No named parameter with the name 'autofillHints'.
      autofillHints: widget.autofillHints,
      ^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/text_form_field.dart:131:3: Context: Found this candidate, but the arguments don't match.
  TextFormField({
  ^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:52:24: Error: Constant evaluation error:
    this.mouseCursor = false,
                       ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:52:24: Context: Expected constant 'false' to be of type 'invalid-type', but was of type 'bool'.
    this.mouseCursor = false,
                       ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:52:10: Context: While analyzing:
    this.mouseCursor = false,
         ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:52:24: Error: Constant evaluation error:
    this.mouseCursor = false,
                       ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:52:24: Context: Expected constant 'false' to be of type 'invalid-type', but was of type 'bool'.
    this.mouseCursor = false,
                       ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.2/lib/src/fields/form_builder_checkbox.dart:52:10: Context: While analyzing:
    this.mouseCursor = false,
         ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882
* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 43s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
//
//
//
//
**flutter doctor**
//
//
//

[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.17134.112],
    locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.48.0)
[√] Connected device (1 available)
//
//
//
****Code****
//
//
//
//

import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:intl/intl.dart';

class FormMaker extends StatefulWidget {
  @override
  _FormMakerState createState() => _FormMakerState();
}

class _FormMakerState extends State<FormMaker> {
  final GlobalKey<FormBuilderState> _fbKey = GlobalKey<FormBuilderState>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('ali'),
      ),
      body: FormBuilder(
        key: _fbKey,
        child: Column(
          children: <Widget>[
            Row(
              children: <Widget>[
                RaisedButton(
                  child: Text('submit'),
                  onPressed: () {
                    if (_fbKey.currentState.saveAndValidate()) {
                      print(_fbKey.currentState.value);
                    }
                  },
                ),
                RaisedButton(
                    child: Text('reset'),
                    onPressed: () {
                      _fbKey.currentState.reset();
                    })
              ],
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by danvick** [comment] 2020-08-15 10:44
Duplicate of #399

**Closed by danvick** 2020-08-15 10:44 UTC
Labels: duplicate
