### ISSUE TITLE
how to handle multiple FormBuilderDropdown onchange

### ISSUE THREAD

**Issue by Lukaalishi** [danvick/flutter_form_builder#391] opened 2020-07-31 21:27 UTC
There should be exactly one item with [DropdownButton]'s value: 28. 
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:flutter/src/material/dropdown.dart':
Failed assertion: line 827 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1'

**Comment by danvick** [comment] 2020-08-02 07:33
Duplicate of #220. Kindly refer

**Closed** 2020-08-09 17:17 UTC
Labels: duplicate, question
