### ISSUE TITLE
reset not working as expected

### ISSUE THREAD

**Issue by mkoorn** [danvick/flutter_form_builder#91] opened 2019-07-10 17:30 UTC
I have have a form with FormBuilderTextField's as per example.
When calling fbKey.currentState.reset(), I can see when stepping through the code, that each field is reset to the initial value.

But when checking the value of the initial value, I see it has the value of the updated textfield which is also shown in the onChange.

I have no idea how this could be happening.

upgraded to v1.7.8+hotfix.3 today, but not sure if that could be an issue.

Any help would be greatly appreciated.

**Comment by stefensuhat** [comment] 2019-07-16 03:57
experiencing same issue.

`reset()` not clearing any value.

**Comment by knaeckeKami** [comment] 2019-07-17 10:42
Could you please post a minimal example where this bug occurs? Just a main.dart file is enough. I'll look into it if I can reproduce it.

**Comment by mkoorn** [comment] 2019-07-25 11:20
@knaeckeKami Thanks for your time. Currently I am swamped with work and in the end I managed by just creating a new key on reset.
I am new to flutter, so it is probably an issue on my side.
should I run into this some other time, I will update with an example.

**Comment by gbtb** [comment] 2019-08-20 12:48
I've faced the same issue. This issue caused by combination of 2 factors:
1) Implementation detail of TextFormField - https://github.com/flutter/flutter/blame/9dce19e96ff36fc36c50d15f57fa20e096a5b29f/packages/flutter/lib/src/material/text_form_field.dart#L141
Simply put, on each (re)build initial value of field will be set to **current** controller.text value. 
2) So, if you make your widget containing form stateful and use setState inside FormBuilder onChanged callback, you get rebuild each time you change field value => reassignment of initialValue. When time comes to reset form, reset "wont work".

**Comment by magillus** [comment] 2019-11-10 23:41
I run into same issue, setting `initialValue: ""` fixed this - feels like work around = maybe by default set that value?

**Comment by danvick** [comment] 2020-07-18 18:23
This issue should be fixed. Feel free to reopen if not.

**Closed by danvick** 2020-07-18 18:23 UTC
Labels: question
