### ISSUE TITLE
TypeAheadField error: Looking up a deactivated widget's ancestor is unsafe

### ISSUE THREAD

**Issue by danielweil** [danvick/flutter_form_builder#605] opened 2020-11-29 20:16 UTC
Hey,

Suddenly, it began to give this error whenever I click on a typeAheadField:

![image](https://user-images.githubusercontent.com/44274213/100552536-91da7c00-3266-11eb-968a-5fb8df556c14.png)

Can anyone look into it?

**Comment by danielweil** [comment] 2020-11-29 20:22
Fixed with version 4.0.2.

**Comment by danielweil** [comment] 2020-11-30 18:32
Issue still continues. Don't know what causes it.

**Comment by danvick** [comment] 2020-11-30 18:38
Hi @danielweil,

I doubt if this issue is one caused by this package or the original typeahead package on which we depend. 

However, we would appreciate it if you were to include sample code for us to try to reproduce the issue.

**Comment by danvick** [comment] 2020-11-30 18:42
The issue has been [reported on the package repo](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/251). Kindly follow up on the repo.

**Comment by danielweil** [comment] 2020-11-30 18:46
I don't know if I can create sample code and reproduce this error. I don't know when it appears and what causes it. My structure is a bit complex to reproduce. But I will look into it and try my best

**Comment by awhitford** [comment] 2020-12-05 10:47
Closing this since this is ultimately not a _Flutter Form Builder_ issue; it is an issue with the underlying typeahead widget: https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/251

**Closed by awhitford** 2020-12-05 10:47 UTC
