### ISSUE TITLE
After using valueTransformer inside FormBuilderTextField , got error type '(String) => Object' is not a subtype of type '((String?) => dynamic)?'

### ISSUE THREAD

**Issue by ashim-kr-saha** [danvick/flutter_form_builder#849] opened 2021-07-08 15:12 UTC
```dart
    FormBuilderTextField(
      name: 'count',
      keyboardType: const TextInputType.numberWithOptions(decimal: false),
      valueTransformer: (value) {
        if (value != '') {
          return int.parse(value);
        }

        return '';
      },
    ),
```

**Comment by dtchau** [comment] 2021-07-22 01:02
I just ran into this issue. If you are still having the issue, you could give the workaround I used a try.
```
    FormBuilderTextField(
      name: 'count',
      keyboardType: const TextInputType.numberWithOptions(decimal: false),
      valueTransformer: (String? value) {
        // Implementation
      },
    )
```

**Comment by dtchau** [comment] 2021-07-22 20:30
Duplicate of #804.

**Closed** 2022-06-09 15:44 UTC
