### ISSUE TITLE
Example starts with errors

### ISSUE THREAD

**Issue by 1g0rrr** [danvick/flutter_form_builder#432] opened 2020-08-25 07:33 UTC
![image](https://user-images.githubusercontent.com/51457/91145550-53a94b80-e6be-11ea-85ac-5c711a444c40.png)
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...
../lib/src/fields/form_builder_range_slider.dart:21:9: Error: Type 'RangeSemanticFormatterCallback' not found.
  final RangeSemanticFormatterCallback semanticFormatterCallback;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.9.1/lib/src/chips_input.dart:88:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.performPrivateCommand
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^
/C:/src/flutter/flutter/packages/flutter/lib/src/services/text_input.dart:813:8: Context: 'TextInputClient.performPrivateCommand' is defined here.
  void performPrivateCommand(String action, Map<String, dynamic> data);
       ^^^^^^^^^^^^^^^^^^^^^
../lib/src/fields/form_builder_range_slider.dart:21:9: Error: 'RangeSemanticFormatterCallback' isn't a type.
  final RangeSemanticFormatterCallback semanticFormatterCallback;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.

**Comment by danvick** [comment] 2020-08-31 11:22
Kindly use the [correct version of the package](https://github.com/danvick/flutter_form_builder#simple-usage) based on the Flutter version you are running.
Duplicate of #436, #382

**Closed** 2022-06-09 15:38 UTC
Labels: duplicate
