### ISSUE TITLE
Compiler message: ../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.1/lib/src/fields/form_builder_checkbox.dart:28:9: Error: Type 'MouseCursor' not found.   final MouseCursor mouseCursor;

### ISSUE THREAD

**Issue by Lukaalishi** [danvick/flutter_form_builder#412] opened 2020-08-11 10:04 UTC
Compiler message:
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.13.1/lib/src/fields/form_builder_checkbox.dart:28:9: Error: Type 'MouseCursor' not found.
  final MouseCursor mouseCursor;

**Comment by danvick** [comment] 2020-08-11 10:26
Duplicate of #399. Kindly refer.

**Closed by danvick** 2020-08-11 10:26 UTC
Labels: duplicate
