### ISSUE TITLE
Localized FormBuilderValidators

### ISSUE THREAD

**Issue by awhitford** [danvick/flutter_form_builder#286] opened 2020-05-22 18:35 UTC
What are your thoughts around Localization?

I built Localization into my app (using [intl_translation](https://pub.dev/packages/intl_translation)), but noticed that I have to override the `errorText` every time I use `FormBuilderValidators`.

Any chance that we could get ARB files for multi-language support?

**Comment by danvick** [comment] 2020-05-24 11:47
I believe this is a duplicate of #17 where I had indicated that I may need help on.

But that was in version 1 of the package which had a lot of internationalization issues with no options.

In case you have time kindly assist on this - given my schedule, it may take some time before I get around to doing it.

**Comment by awhitford** [comment] 2020-06-11 00:10
Right now, this is more of a long-term issue, but I will be happy to help once this is important to me.

**Comment by danvick** [comment] 2020-07-08 19:50
Hi @awhitford,
I'm closing this since it's a duplicate of #17. Kindly follow the conversation there.

**Closed by danvick** 2020-07-08 19:50 UTC
Labels: duplicate, enhancement
