### ISSUE TITLE
Async validation

### ISSUE THREAD

**Issue by RodolfoSilva** [danvick/flutter_form_builder#219] opened 2020-01-16 11:44 UTC
A few times after sending data to the backend, the server will respond with backend validation. How can I set an error message for for a specific field?

@danvick do you have any suggestion how can I do that?

**Comment by danvick** [comment] 2020-01-16 16:25
As it is currently in Flutter, there's no way of passing up an error to a FormField. 
I've been working on the next major version of the package with this as one of the features. 

Problem is currently, I'm a bit short on time.

**Comment by RodolfoSilva** [comment] 2020-01-16 18:30
Thanks @danvick 😄

**Comment by RodolfoSilva** [comment] 2020-01-16 18:33
Maybe I can help you, I'm short on time too. But if I can help, tell me.

**Comment by ronaldcurtis** [comment] 2020-04-03 05:40
@RodolfoSilva Just a heads up that I have found a work-around, inspired by this article: https://medium.com/@nocnoc/the-secret-to-async-validation-on-flutter-forms-4b273c667c03

Basically, what I did was (condensed code):

```dart
class _EmailPasswordFormState extends State<EmailPasswordForm> {
  final GlobalKey<FormBuilderState> _fbKey = GlobalKey<FormBuilderState>();
 
  // We update this boolean after our async function runs
  bool _emailHasBeenTaken = false;

  // Create this custom validator that references the above variable
  FormFieldValidator validateEmailIsUnique() {
    return (val) => _emailHasBeenTaken ? "This email has been taken" : null;
  }

// ...Skipping down to where we add validators:
validators: [
  FormBuilderValidators.required(),
  FormBuilderValidators.email(),
  // Add your validator function
  validateEmailIsUnique(),
],
        
// ...Skipping down where we submit the form:
onPressed: () {
  // Run our synchronous validators first:
  _fbKey.currentState.saveAndValidate()
  // Emulating an async call here:
  Future.delayed(Duration(seconds: 1), () {
    setState(() {
      // Pretend the response says email is not unique:
      _emailHasBeenTaken = true;
    });
    
    // Re-run the validations to show the error message
    _fbKey.currentState.saveAndValidate();
  });
}
```

I hope that helps!

**Comment by danvick** [comment] 2020-07-07 11:43
> Maybe I can help you, I'm short on time too. But if I can help, tell me.

Hi @RodolfoSilva,
I have made some progress in the v4.0.0 milestone. I may need your help in testing it out. Thanks in advance.

**Comment by RodolfoSilva** [comment] 2020-07-07 12:51
Ok @danvick , I'll check later :D

**Comment by danvick** [comment] 2020-07-22 23:13
I'm marking this as a duplicate of #123.

**Closed by danvick** 2020-07-22 23:13 UTC
Labels: duplicate, enhancement
