### ISSUE TITLE
Form Reset Not Working [ver 6.0.1]

### ISSUE THREAD

**Issue by Shiba-Kar** [danvick/flutter_form_builder#848] opened 2021-07-07 06:28 UTC
I have a form most of them is textFields i have passed a initialvalue. when i reset the from  using foemkey nothing happens.

**Comment by edwin0401** [comment] 2021-09-05 09:05
I got the same. Do you have idea to fix it?

**Comment by deandreamatias** [comment] 2022-06-10 14:00
This still an issue?

**Comment by markfili** [comment] 2022-06-21 14:23
I can't even click on the reset icon, it always opens the input dialog

**Comment by deandreamatias** [comment] 2022-06-21 14:28
@markfili Can provide details please

- **Platform:** 
- **Device information:**  
- Simple code smaple

**Comment by markfili** [comment] 2022-06-22 05:53
oh, I forgot, I think OP meant that calling `_formKey.currentState!.fields['date']?.reset();` does not reset the field which is what I found, too. you can replace `.didChange(null)` with `reset()` in `resetIcon`'s `onPressed` method in the above example to test it out

**Comment by deandreamatias** [comment] 2022-06-22 10:54
@markfili This happens only with `FormBuilderDateTimePicker`?

**Comment by deandreamatias** [comment] 2022-06-22 10:57
@markfili I think that this situation is duplicated from #859

**Comment by markfili** [comment] 2022-06-23 07:54
> @markfili This happens only with `FormBuilderDateTimePicker`?

yes! just tried the example app from the master branch, only DateTimePicker has this issue, DateRangePicker and TextField work as intended.

**Comment by deandreamatias** [comment] 2022-06-23 08:43
I think that this is because you use initialValue and initialTime at same time. These generate conflict.
I will close this issue and move all to #859

**Closed by deandreamatias** 2022-06-23 08:43 UTC
Labels: bug
