### ISSUE TITLE
datetime picker initialDate does not work and resets value when close button is clicked

### ISSUE THREAD

**Issue by FatihAydin52** [danvick/flutter_form_builder#120] opened 2019-08-24 17:01 UTC
Version:   flutter_form_builder: ^3.4.1

datetime picker initialDate does not work and resets value when close button is clicked.

```
FormBuilderDateTimePicker(
       attribute: "date",
       inputType: InputType.date,
       format: DateFormat("yyyy-MM-dd"),
       resetIcon: null,
       decoration: InputDecoration(labelText: S.of(context).date),
       initialDate: counter.dateTime,
       validators: [FormBuilderValidators.required()],
),
```

![datetime](https://user-images.githubusercontent.com/14280894/63640507-e11c1f00-c6a9-11e9-9ab9-ffdb4a043734.gif)

**Comment by danvick** [comment] 2019-08-30 08:37
Hi @FatihAydin52,
Kindly check out version 3.5.0 which contains a fix for this. 
If you could, please confirm whether the issue is fixed or not.

**Comment by danvick** [comment] 2019-09-03 09:13
Kindly have a look at ^3.5.1

**Closed by danvick** 2019-09-03 09:13 UTC
