### ISSUE TITLE
Build Fails | 3.11.3

### ISSUE THREAD

**Issue by NiranjanShah** [danvick/flutter_form_builder#400] opened 2020-08-06 16:49 UTC
Build is failing with the below error.

../../Dev%20Tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.9.0/lib/src/chips_input.dart:393:3: Error: Type 'AutofillScope' not found.
  AutofillScope get currentAutofillScope => null;

PS: flutter_chips_input is not used individually by the project (i verified the library is part of flutter_form_builder) . Kindly assist, as it has stalled the project release.

**Comment by danvick** [comment] 2020-08-06 17:47
Kindly upgrade to v3.13.0 if using the latest version of Flutter (v1.20).

Duplicate of #399.

**Closed by danvick** 2020-08-06 17:47 UTC

**Comment by NiranjanShah** [comment] 2020-08-06 20:04
it is flutter 1.17.6.
Form builder version  3.11.3
