### ISSUE TITLE
Form doesn't work properly after a Navigator.push

### ISSUE THREAD

**Issue by benoitverstraete** [danvick/flutter_form_builder#33] opened 2019-03-19 14:33 UTC
Hi,

I try to display the form after a Navigator.of(context).push but I encounter some issues.

With the typeAHead : the suggestions are not displayed while I write something in the textField (if the suggestion is finally displayed, the value is not set).

With the datePicker and timePicker : after choosing a date/time, the value is not correctly set.

Do you experience the same issues ? Or maybe is there something's else to do with the Navigator ?

Here is an example : [https://gist.github.com/benoitverstraete/9bb9f23b91d35c4f69effc54ae8ff446](https://gist.github.com/benoitverstraete/9bb9f23b91d35c4f69effc54ae8ff446)

Thanks a lot !

**Comment by danvick** [comment] 2019-03-19 16:59
Hi @benoitverstraete, 
Thanks for bringing this to my attention.

1. There's a minor bug in your code where you are using `Navigator.of(context).push`. Take note that in Dart you can't combine `=>` with `{}`, refer [here](https://stackoverflow.com/a/15804343/2949916). I changed to the code below and it now functions as expected.
```
onPressed: () {
        Navigator.of(context)
              .push(MaterialPageRoute(builder: (context) => MyHomePage()));
        },
```

2. I've noticed that problems with typeAhead and Date/Time Pickers are caused by a [bug in flutter](https://github.com/flutter/flutter/issues/9471) especially the latter versions. You'll notice this line in your console `W/IInputConnectionWrapper( 9846): getTextBeforeCursor on inactive InputConnection`. I'm working on a workaround to be published ASAP, after which I'll notify you.

Thanks again

**Comment by benoitverstraete** [comment] 2019-03-20 08:04
Thanks for your feedback, @danvick

**Comment by danvick** [comment] 2019-03-20 18:45
DatePicker, TimePicker issues should be fixed according to my tests. Meanwhile, I'm going ahead to close this issue, feel free to reopen or open another one in case you encounter any anomalies

**Closed by danvick** 2019-03-20 18:45 UTC
