### ISSUE TITLE
Issue: Input fields keep loosing focus

### ISSUE THREAD

**Issue by jasonlaw** [danvick/flutter_form_builder#40] opened 2019-03-26 00:21 UTC
Hi @danvick ,
After upgrading to version v2.0, my input fields keep loosing focus.

Below is not from my screen, but the problem is exactly the same.
![1d8b82c2-a6dd-11e6-8f4c-31b772a500fd](https://user-images.githubusercontent.com/107820/54962472-f75d6c00-4f9f-11e9-86a1-6f382ea9d426.gif)

Below is my code.
![2019-03-26_081546](https://user-images.githubusercontent.com/107820/54962497-0e9c5980-4fa0-11e9-9569-a3d0ac9eea22.png)

**Comment by jasonlaw** [comment] 2019-03-26 00:55
To add more info, I found that the form is always redraw when a input is getting focus.

These printed whenever I try to focus on the input textbox.
![2019-03-26_084404](https://user-images.githubusercontent.com/107820/54963734-c03d8980-4fa4-11e9-8268-efabafcb2c72.png)

**Comment by jasonlaw** [comment] 2019-03-26 01:26
I have made a small changed in the code and it seems working, however, the behavior is still somewhat strange due to the formKey keep changing.

![2019-03-26_092215](https://user-images.githubusercontent.com/107820/54964886-1d3b3e80-4fa9-11e9-8268-2463dcb2a2dd.png)

**Comment by danvick** [comment] 2019-03-26 06:02
Hey @jasonlaw,

Thanks for the help, you're the best.

Seems like I accidentally merged another branch which I was doing some experimental stuff on.

**Comment by danvick** [comment] 2019-03-26 06:29
@jasonlaw To avoid key changing, don't declare the global key inside your build method.

**Comment by jasonlaw** [comment] 2019-03-26 06:42
@danvick, thanks for the quick response. Indeed after moving out from the build method, it works normally now, you are awesome! :)

**Closed** 2019-03-27 08:24 UTC

**Comment by benoitverstraete** [comment] 2019-04-04 13:33
Hi,

I have the same behavior even if I move the global key in the class. I upgraded the package to the latest version (flutter_form_builder: ^2.0.3). It is impossible to enter a value in the fields.

Here is a sample of my code :

```
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';

class ActivityPage extends StatelessWidget {
  final GlobalKey<FormBuilderState> _fbKey = GlobalKey();

  var data;

  final allCountries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('New activity'),
      ),
      body: SingleChildScrollView(
        child: FormBuilder(context, key: _fbKey, controls: [
          FormBuilderInput.typeAhead(
            decoration: InputDecoration(labelText: "Country"),
            attribute: 'country',
            // require: true,
            itemBuilder: (context, country) {
              return ListTile(
                title: Text(country),
              );
            },
            suggestionsCallback: (query) {
              if (query.length != 0) {
                var lowercaseQuery = query.toLowerCase();
                return allCountries.where((country) {
                  return country.toLowerCase().contains(lowercaseQuery);
                }).toList(growable: false)
                  ..sort((a, b) => a.toLowerCase().indexOf(lowercaseQuery).compareTo(b.toLowerCase().indexOf(lowercaseQuery)));
              } else {
                return allCountries;
              }
            },
          ),
          FormBuilderInput.textField(
            type: FormBuilderInput.TYPE_TEXT,
            attribute: "name",
            decoration: InputDecoration(labelText: "Full Name"),
            value: "John Doe",
          ),
        ]),
      ),
    );
  }
}
```

Could you please help me with this ?

Thanks a lot !

**Comment by danvick** [comment] 2019-04-04 13:54
Hi @benoitverstraete,
I've been unable to reproduce your error. Could you kindly share your version of flutter or the result of your `flutter doctor`

**Comment by danvick** [comment] 2019-04-04 13:56
You could also try converting your widget to a StatefulWidget especially if you want to make use of the data variable to get the result of your form

**Comment by benoitverstraete** [comment] 2019-04-04 13:57
Yes, sure : 

```
C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale en-GB)
    • Flutter version 1.2.1 at C:\src\flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\bve\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] VS Code (version 1.32.3)
    • VS Code at C:\Users\bve\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by benoitverstraete** [comment] 2019-04-04 14:05
@danvick this bug disappear when I convert the StatelessWidget to a Stateful one, thanks !lba

But, I keep getting the error from the issue #33 for the typeAhead control...

**Comment by danvick** [comment] 2019-04-04 14:31
@benoitverstraete I'm quite sorry for the inconveniences. The package, as I later realized has quite an issue with state management. That's why I've taken to do complete rewrite coming out as version 3.0.0, in fact I've released a beta version of it just a few hours ago.

Feel free to test it out. I doubt if there will be major API changes before it's release

**Comment by benoitverstraete** [comment] 2019-04-04 14:52
@danvick Ok, I will take a look at the new version and will open another issue if I encounter some issues.
