### ISSUE TITLE
FocusNode leak in FormBuilderTouchSpin

### ISSUE THREAD

**Issue by danielweil** [danvick/flutter_form_builder#603] opened 2020-11-28 21:46 UTC
I have a page structure inside a button, and this is the only field having focusNode leak problems. I might not use it anymore and go with the text field with numeric keyboard instead. Just wanted to keep a note on it.

I was able to fix it initializing a FocusNode for each field in each page, but I wonder why the other fields work without doing this.

**Comment by awhitford** [comment] 2020-12-05 08:41
I took a quick look at the _Touch Spin_ source code and I don't see an opportunity for it to leak Focus Nodes.  We will need to see more information, like sample code or a stack trace.

**Comment by awhitford** [comment] 2020-12-11 20:11
Closing this because I think `FocusNode` leaks have been resolved with Version 4.x.

We can reopen if you have a reproducible test case.

**Closed by awhitford** 2020-12-11 20:11 UTC
