### ISSUE TITLE
Pull #599 broke FormBuilderTypeAhead generics

### ISSUE THREAD

**Issue by hasbean** [danvick/flutter_form_builder#623] opened 2020-12-06 16:50 UTC
https://github.com/danvick/flutter_form_builder/pull/599

I've been using it this way 

`FormBuilderTypeAhead<Category>(......)`

I'm getting the error `type 'String' is not a subtype of type 'Category' in type cast` specifically on line 393

`didChange(_typeAheadController.text as T);`

Which obviously won't work since _typeAheadController.text will always be a String.

Thanks!  Love the plugin!

**Comment by dmoeyers** [comment] 2020-12-06 22:04
I can confirm I have a similar issue...

**Comment by akreienbring** [comment] 2020-12-08 16:32
Glad I found this, because I was searching for hours for that TypeError in my code...
And I think the following may be related: 

With version 3.1.4 this code was working:

```
                            FormBuilderTypeAhead<Manufacturer>(
                              decoration: const InputDecoration(
                                labelText: 'Manufacturer',
                              ),
                              initialValue: _device.manufacturer,
                              attribute: 'manufacturer',
                              onChanged: (manufacturer) {
                                logger.log(
                                    "Setting manufacturerName to " +
                                        manufacturer.name,
                                    name: _logCategory);
                                logger.log(
                                    "Setting manufacturerId to " +
                                        manufacturer.manufacturerId.toString(),
                                    name: _logCategory);
                                //some usage of the id here...
                              },
                              itemBuilder:
                                  (context, Manufacturer manufacturer) {
                                return ListTile(
                                  title: Text(manufacturer.name),
                                );
                              },
                              selectionToTextTransformer: (Manufacturer c) =>
                                  c.name,
                              suggestionsCallback: (query) {
                                if (query.isNotEmpty) {
                                  var lowercaseQuery = query.toLowerCase();
                                  return _manufacturers
                                      .where((manufacturer) {
                                    return manufacturer.name
                                        .toLowerCase()
                                        .contains(lowercaseQuery);
                                  }).toList(growable: false)
                                        ..sort((a, b) => a.name
                                            .toLowerCase()
                                            .indexOf(lowercaseQuery)
                                            .compareTo(b.name
                                                .toLowerCase()
                                                .indexOf(lowercaseQuery)));
                                } else {
                                  return _manufacturers;
                                }
                              },
                              validators: [
                                FormBuilderValidators.required(
                                    errorText: AppLocalizations.instance
                                        .text('info_required_field')),
                                FormBuilderValidators.maxLength(
                                  50,
                                  errorText: AppLocalizations.instance
                                          .text('info_max_length') +
                                      "50",
                                ),
                              ],
                            ),
```

It let me search for a manufacturer name and on the selection it gave me the id. I also used it to introduce a new manufacturer when a new name was entered (not in the list) because the id then was obviously not set.

Besides the error mentioned by the OP, I've an additional problem with version 4.0.2:

In case of a new entry I want to validate the length of the name. 

```
                              validator: FormBuilderValidators.compose(
                                [
                                  FormBuilderValidators.required(context,
                                      errorText: AppLocalizations.instance
                                          .text('info_required_field')),
                                  FormBuilderValidators.maxLength(      //<--- Error here!
                                    context,
                                    25,
                                    errorText: AppLocalizations.instance
                                            .text('info_max_length') +
                                        "50",
                                  ),
                                ],
                              ),

```

But I get an error on the second FormBuilderValidator (maxLength) saying: "The element type 'String Function(String)' can't be assigned to the list type 'String Function(Manufacturer)'"

So please, If you fix this and my point is related, I'll be happy to test the next release!

**Comment by akreienbring** [comment] 2021-01-05 14:11
The issue still exists with release 4.2.0. Which one is the duplicate issue?

**Comment by WilliamCunhaCardoso** [comment] 2021-01-07 12:33
> The issue still exists with release 4.2.0. Which one is the duplicate issue?

https://github.com/danvick/flutter_form_builder/issues/674 I believe this one is related

**Comment by deandreamatias** [comment] 2022-06-09 19:57
This still a issue?

**Comment by deandreamatias** [comment] 2022-06-24 15:35
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)

**Closed by deandreamatias** 2022-06-24 15:35 UTC
Labels: duplicate, awaiting author response
