### ISSUE TITLE
Is this package support for iOS?

### ISSUE THREAD

**Issue by Sravankumar28** [danvick/flutter_form_builder#235] opened 2020-03-02 11:56 UTC
I am using this package for hybrid app but this is not working in iOS.can you please help me out.

**Comment by danvick** [comment] 2020-03-27 18:44
Hi @Sravankumar28,
Not currently but we're planning for it in future.

**Comment by awhitford** [comment] 2020-06-11 15:09
I am using Flutter Form Builder in an app that is compiled to iOS and Android.  _What is the issue?_

**Comment by danvick** [comment] 2020-07-18 18:17
Closed since it's a duplicate of #22. PRs are welcome

**Closed by danvick** 2020-07-18 18:17 UTC
Labels: duplicate, help wanted
