### ISSUE TITLE
readOnly is not working in FormBuilderDateTimePicker

### ISSUE THREAD

**Issue by shashikantshaale** [danvick/flutter_form_builder#179] opened 2019-11-27 10:12 UTC
Even after setting readOnly to true in FormBuilderDateTimePicker, user can change the date.

here's my code

```
FormBuilderDateTimePicker(
                  readOnly: true,
                  attribute: 'dob',
                  firstDate: DateTime(1850),
                  initialDate: DateTime.now().subtract(Duration(days: 365 * 6)),
                  lastDate: DateTime.now().subtract(Duration(days: 365 * 5)),
                  inputType: InputType.date,
                  resetIcon: Icon(Icons.close),
                  initialDatePickerMode: DatePickerMode.day,
                  format: DateFormat("MMM d, yyyy "),
                  decoration: InputDecoration(
                    labelText: 'Date of Birth',
                  ),
                ),
```

Version using _**flutter_form_builder: ^3.6.1**_

**Comment by danvick** [comment] 2019-11-30 12:15
Hi @shashikantshaale,
Thanks fo bringing this to my attention

**Comment by danvick** [comment] 2019-12-05 11:33
Fixed in v3.7.0. Feel free to reopen on case of any more feedback.

**Comment by shashikantdurge** [comment] 2020-02-17 08:12
This bug still exists.
Changing **_readOnly_** of _FormBuilder_  does not change **_readOnly_** of _FormBuilderDateTimePicker_

**Comment by shashikantdurge** [comment] 2020-02-17 08:13
@danvick Can you reopen this issue

**Closed** 2020-02-17 09:36 UTC
Labels: bug

**Comment by shashikantshaale** [comment] 2020-02-17 09:39
That was very quick. Super

**Comment by danvick** [comment] 2020-02-17 09:53
I've just released a hotfix on pub. Kindly check and confirm if the problem is fixed

**Comment by shashikantshaale** [comment] 2020-02-17 10:09
Yeah it seems fixed!
