### ISSUE TITLE
FormBuilderDropdown broke inside futurebuilder

### ISSUE THREAD

**Issue by zlamlam10** [danvick/flutter_form_builder#649] opened 2020-12-18 21:47 UTC
I put the FormBuilderDropdown inside FutureBuilder so when I press on it will rebuild infinitely and will not enter the FormBuilderDropdown

```
 FutureBuilder(
                          future: widget.fetchBrands(yearValue),
                          builder:
                              (BuildContext context, AsyncSnapshot snapshot) {
                            var snap = snapshot.data;
                            if (snapshot.connectionState ==
                                ConnectionState.waiting) {
                              return Center(
                                child: CircularProgressIndicator(),
                              );
                            }
                            if (snapshot.hasError) {
                              if (yearValue == null) {
                                return Container(
                                  child: Text(
                                    "Select the manufacture year to Select Brand",
                                    style: TextStyle(
                                      color: Colors.red[800],
                                      fontSize: 16,
                                    ),
                                    overflow: TextOverflow.visible,
                                  ),
                                );
                              }
                              return Center(
                                child: new Text('Error'),
                              );
                            }
                            snap.forEach((key, brand) {
                              brands.add(brand['make']);
                            });

                            brands = brands.toSet().toList();
                            brands.sort();
                            return
                                /**
                  Brands and focusNode = 1
                 */
                                FormBuilderDropdown(
                              key: ValueKey("Brands"),
                              name: "Brands",
                              items: brands
                                  .map(
                                    (e) => DropdownMenuItem<String>(
                                      child: Text(e),
                                      value: e,
                                    ),
                                  )
                                  .toList(),
                              validator: FormBuilderValidators.compose(
                                [
                                  FormBuilderValidators.required(
                                    context,
                                  )
                                ],
                              ),
                              decoration: InputDecoration(
                                labelText: 'Brands',
                                labelStyle:
                                    Theme.of(context).textTheme.display1,

                                //alignLabelWithHint: true,
                              ),
                              focusNode: _focusNode[1],
                              hint: Text('Select Brand'),
                              allowClear: true,
                              onChanged: (value) {
                                setState(() {
                                  brandValue = value;
                                  carValue = null;
                                  carsName.clear();
                                  FocusScopeNode currentFocus =
                                      FocusScope.of(context);

                                  if (!currentFocus.hasPrimaryFocus) {
                                    currentFocus.unfocus();
                                  }
                                });
                              },
                              onSaved: (newValue) => _brand = newValue,
                              style: Theme.of(context).textTheme.display1,
                            );
                          },
                        ),
```

before the update its work fine for me

**Comment by awhitford** [comment] 2021-01-08 05:21
@zlamlam10 I think your problem is this line:
```dart
                          future: widget.fetchBrands(yearValue),
```
This code will create a brand new Future for each `build` call -- that is not desirable.  You only want to trigger a new future during `initState` or when `yearValue` changes.

Closing this since the issue isn't really related to _Flutter Form Builder_.

**Closed by awhitford** 2021-01-08 05:21 UTC
